### ISSUE TITLE
Double function

### ISSUE THREAD

**Issue by jimbo2150** [SchoolyB/My-first-loan-calculator#1]
https://github.com/SchoolyB/My-first-loan-calculator/blob/7f95640e7f427531f8503dcbbea0a1689e4803b4/Loan%20Calculator1.py#L43

This function returns void, so the subsequent if/elif/else statement will always be else and the question will be asked twice. Consider putting it at the end of the function.

**Comment by jimbo2150** [comment]
The same problem is also in the elif block.

**Comment by SchoolyB** [comment]
Thank you for the feedback. It definitely helped in my learning process. I took care of it!👍🏾
